import React, {useRef, useEffect} from 'react'
import { graphql } from 'gatsby'
import Layout from '../components/layout'
import Seo from '../components/seo'
import * as styles from './articles.module.css'
import {GatsbyImage} from 'gatsby-plugin-image'